### ISSUE TITLE
Create optional flag on steps

### ISSUE THREAD

**Issue by Somtom** [Somtom/SetMeUp#1]
# Problem
Not all steps need to be executed. We also want to support optional steps where the user can decide

# Solution idea
We could have a `optional` flag on the steps, e.g.:

```yaml

  - script: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    description: "Install ZSH and Oh My ZSH"
    completion_check: '[ -e ~/.oh-my-zsh ]'
    optional: true
  ```
